#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? DDD
#?? 1.0.0
##?
##? Usage:
##?   ddd hexagonal <path>
docs::parse "$@"

mkdir -p "$path/application"
touch "$path/application/__init__.py"
mkdir -p "$path/domain"
touch "$path/domain/__init__.py"
mkdir -p "$path/infrastructure"
touch "$path/infrastructure/__init__.py"

echo "😬 Dooone!"