#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Delete image from images
#?? 1.0.0
##?
##? Usage:
##?   connect
docs::parse "$@"

if docker images >/dev/null 2>&1; then
  container=$(docker images | awk '{if (NR!=1) print $1 ": " $(NF)}' | fzf --height 40%)

  if [[ -n $container ]]; then
    container_id=$(echo $container | awk -F ': ' '{print $1}')
    echo "$container_id"
    docker rmi $container_id 
  else
    echo "You haven't selected any container! ༼つ◕_◕༽つ"
  fi
else
  echo "Docker daemon is not running! (ಠ_ಠ)"
fi

