#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Compress only modified files
#?? 1.0.0
##?
##? Usage:
##?   compress_modified
docs::parse "$@"


zip ../modified-files.zip $(git diff --name-only HEAD)
