#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/git.sh"
source "$DOTFILES_PATH/scripts/core/documentation.sh"

##? Compress only modified files
#?? 1.0.0
##?
##? Usage:
##?   compress_modified
docs::eval "$@"


zip ../modified-files.zip $(git diff --name-only HEAD)
