#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Install Calibre ebook managment
#?? 1.0.0
##?
##? Usage:
##?   install_calibre
docs::parse "$@"

# download latest calibre. check https://calibre-ebook.com/download_linux
sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

