#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Install Docker-ce and add $USER to docker group
#?? 1.0.0
##?
##? Usage:
##?   install_docker
docs::parse "$@"


# apt over https
sudo apt-get install apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

# Key GPG docker official
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# Add stable repository
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable" 

sudo apt-get update && sudo apt-get install docker-ce

# Execute docker without being sudo
sudo usermod -aG docker $USER

# install 1.26.2 docker-compose, check releases https://github.com/docker/compose/releases
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
$(echo docker-compose --version)
