#!/usr/bin/env bash

set -euo pipefail

##? Install Node and set a global folder in $HOME
#?? 1.0.0
##?
##? Usage:
##?   install_node

exports="${DOTFILES_PATH}/shell/_exports/exports.sh"
npm_path="${HOME}/.npm-global"

sudo apt install nodejs
#$(echo node –version)

sudo apt install npm
#$(echo npm –version)


echo "Creating global folder ${npm_path}"

if [ ! -d ${npm_path} ]; then
    mkdir -p ${npm_path}
fi

echo "Setting as npm config prefix ${npm_path}"
npm config set prefix '~/.npm-global'

if ! grep -qxF 'export NPM_PACKAGES="${npm_path}"' ${exports} ; then 
    echo -e 'Stablishing node path in ${npm_path}...'
    envfix='
export NPM_PACKAGES="%s"
export NODE_PATH="$NPM_PACKAGES/lib/node_modules${NODE_PATH:+:$NODE_PATH}"
export PATH="$NPM_PACKAGES/bin:$PATH"
'

    printf "${envfix}" ${npmdir} >> ${exports}
fi